version: '2'
services:
    runner-app:
        image: runner
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://runner-mysql:3306/runner?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://runner-elasticsearch:9200
        ports:
            - 8080:8080
    runner-mysql:
        extends:
            file: mysql.yml
            service: runner-mysql
    runner-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: runner-elasticsearch
